version: "3.8"
services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=linhdev
      - MYSQL_ROOT_PASSWORD=null
    ports:
      - "3309:3306"
    expose:
      - 33060

  backend:
    build:
      context: ../../BE_ExpressJs
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=33060
      - DB_HOST=database
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
